"use strict";
// Only the public API origin is emitted. Never serialize process.env.
const fs = require("node:fs");
const path = require("node:path");

function buildConfig() {
  const raw = (process.env.API_BASE_URL || "").trim();
  if (!raw) throw new Error("API_BASE_URL is required.");
  let url;
  try { url = new URL(raw); } catch { throw new Error("API_BASE_URL must be an HTTP(S) origin."); }
  if (!/^https?:$/.test(url.protocol) || url.username || url.password ||
      url.search || url.hash || !/^\/*$/.test(url.pathname) || /[\s\\]/.test(raw)) {
    throw new Error("API_BASE_URL must be an HTTP(S) origin without credentials, path, query or fragment.");
  }
  const output = '"use strict";\n// Generated by build-config.js from the public API_BASE_URL.\n' +
    'const API_BASE_URL = ' + JSON.stringify(url.origin) + ';\n';
  fs.writeFileSync(path.join(__dirname, "config.js"), output, "utf8");
}
try { buildConfig(); } catch {
  console.error("Build failed: API_BASE_URL must be set to a valid public HTTP(S) API origin; config generation failed.");
  process.exitCode = 1;
}
